In [67]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import precision_recall_curve
from sklearn.inspection import permutation_importance
import matplotlib.pyplot as plt
import os

In [37]:
#test_train_data = pd.read_csv("cleaned_data/test_train_data.csv")
#d3 = pd.read_csv("cleaned_data/d3.csv")
#modelling_data = pd.read_csv("cleaned_data/modelling_data.csv")
fulld1 = pd.read_csv("cleaned_data/fulld1.csv")

if os.path.exists('cleaned_data/d3_updated.csv'):
    d3 = pd.read_csv('cleaned_data/d3_updated.csv')
    print(f"Loaded d3_updated — anomaly count: {d3['is_anomaly'].sum()}")
else:
    d3 = pd.read_csv('cleaned_data/d3.csv')
    print(f"Loaded original d3 — anomaly count: {d3['is_anomaly'].sum()}")

Loaded d3_updated — anomaly count: 148

In [64]:
#creating my datasets for testing, training, modeling 

test_train_data = fulld1[
    fulld1['name'].isin(list(d3['name']))
]
exclude = test_train_data['name']

modelling_data = fulld1[~fulld1['name'].isin(exclude)]

#test_train_data['is_anomaly'] = test_train_data['is_anomaly'].fillna(0).astype(int)





test_train_data = test_train_data.merge(d3, on=['name', 'date', 'set'], how='left')
#test_train_data = test_train_data.merge(olympic, on=['name', 'date', 'set'], how='left')

test_train_data['is_anomaly'] = test_train_data[
    ['is_anomaly_x', 'is_anomaly_y']
].max(axis=1).fillna(0).astype(int)

test_train_data = test_train_data.drop(columns=['is_anomaly_x', 'is_anomaly_y'])


# test_train_data = test_train_data.drop(columns=['is_anomaly_x', 'is_anomaly_y'])


test_train_data

# print(len(good2))

# print(len(good))



# for i in good:
#     if i not in good2:
#         print(i)
        

print(test_train_data['is_anomaly'].sum())
#merged = olympic_keys.merge(df, on=['name', 'date', 'set'], how='left', indicator=True)


#n = test_train_data.loc[test_train_data['is_anomaly'] == 1, 'name']


# noe = []
# for i in n:
#     if i not in train_d:
#        noe.append(i)

#     elif i not in test_d:
#         noe.append(i)


# n

143

In [39]:
#train/test split 80/20 spit

d3_names = d3['name'].unique()
d3_only = test_train_data[test_train_data['name'].isin(d3_names)].copy()


unique_athletes = d3_only['name'].unique()

train_athletes, test_athletes = train_test_split(
    unique_athletes,
    test_size=0.2,
    random_state=42
)

train_df = d3_only[d3_only['name'].isin(train_athletes)]
test_df  = d3_only[d3_only['name'].isin(test_athletes)]

drop_cols = ['name', 'date', 'datetime', 'set','days_since_last_test']
train_df = train_df.drop(columns=drop_cols)
test_df  = test_df.drop(columns=drop_cols)

X_train = train_df.drop(columns=['is_anomaly'])
y_train = train_df['is_anomaly']
X_test  = test_df.drop(columns=['is_anomaly'])
y_test  = test_df['is_anomaly']

In [40]:
print(f"Train size: {len(X_train)} rows, {y_train.sum()} anomalies")
print(f"Test size:  {len(X_test)} rows, {y_test.sum()} anomalies")

train_names = set(train_df.index)
overlap = set(train_athletes) & set(test_athletes)
print(f"Athlete overlap between train and test: {len(overlap)}")

Train size: 4502 rows, 109 anomalies
Test size:  1282 rows, 34 anomalies
Athlete overlap between train and test: 0

In [41]:
train_set = set(train_athletes)
d3_set = set(d3['name'].unique())
overlap = train_set.intersection(d3_set)

print("Number of overlapping names(training):", len(overlap))
print(overlap)

Number of overlapping names(training): 96
{'andrew clarke', 'emmanuella frimpomaa', 'cameron davenport', 'konstantinos dellas', 'ian scott', 'aidan plummer', 'vasileios moiras', 'conor mcnally', 'luke lowery', 'lilly venezia', 'ava carlson', 'max livingston', 'jamal cooper', 'abby reger', 'mk daly', 'waleed qadir', 'emmett croteau', 'dylan baumgarth', "colin o'garro", 'brooke hess', 'grayson saunier', 'audrey marin', 'izzy mundee', 'jack mulholland', 'riley grosdidier', 'riley dumigan', 'marco dzamba', 'zyion brown', 'nick marinaro', 'john stenberg', 'george hawley', 'debra hill', 'tyler juhlin', 'godson ajoku', 'francisco caballero', 'isaiah golonka', 'john bancone', 'olivia lyman', 'samuel washington', 'panagiotis karagiorgis', 'kyle meier', 'tyson grimm', 'ahmir braxton', 'ava davis', 'chris miller', 'carson franks', 'caroline haggerty', 'patrick campbell', 'matthew scheible', 'mary lundregan', 'oskari vuorio', 'mcallister burke', 'elliott fee', 'emily garrard', 'thai brown', 'olivia lawlor', "fiona o'keefe", 'justin ruff', 'vasean washington', 'isabel kirby', 'michael solomon', 'maxwell wentz', 'riley imamura', 'zoe schaffer', 'konstantin spork', 'cameron lee', 'khari mayeux', 'jabari johnson', 'quinn stankovits', 'sean harmon', 'sean williams', 'max voigt', 'justice malone', 'camden rush', 'catherine erb', 'ella snyder', 'cwen wilson', 'emma symon', 'nicholas lemon', 'roland waguespack', 'mitchell monte', 'raul vargas', 'jaden cummings', 'michael betsy', 'frank argilagos', 'chris corbo', 'darius crowther', 'joshua johnson', 'spencer reagan', 'katie hansen', 'samantha gresham', 'taysire williams', 'lourdes lauterborn', 'sierra santiago', 'john prince', 'miles groom'}

In [42]:
test_set = set(test_athletes)
d3_set = set(d3['name'].unique())
overlap = test_set.intersection(d3_set)

print("Number of overlapping names(testing):", len(overlap))
print(overlap)

Number of overlapping names(testing): 25
{'steve simpkins', 'luke armistead', 'hailey rorick', 'florentina terra', 'delby lemieux', 'gergely hudak', 'calum langmuir', 'hudson kohler', 'kellie sutton', 'yuseph mustafa', 'emma olausson', "grayson o'bara", 'sarah shelburne', 'joe onuwabhagbe', 'bruce williams', 'lila browne', 'chase engdahl', 'sonoma adams', 'niquis ratcliff', 'kenneth edwards', 'immanuel johnson', "no'koi maddox", 'andrew belles', 'abayomi babalola', 'kate riley'}

In [43]:
print(f"Train anomalies: {y_train.sum()} out of {len(y_train)} rows")
print(f"Test anomalies: {y_test.sum()} out of {len(y_test)} rows")

# Check the ratio is roughly similar
print(f"\nTrain anomaly rate: {y_train.sum()/len(y_train)*100:.2f}%")
print(f"Test anomaly rate: {y_test.sum()/len(y_test)*100:.2f}%")

Train anomalies: 109 out of 4502 rows
Test anomalies: 34 out of 1282 rows

Train anomaly rate: 2.42%
Test anomaly rate: 2.65%

In [44]:
#Pipe line functions for supervised models

def build_pipeline(model):
    return Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler()),
        ('model', model)
    ])

models = {
    'Logistic Regression': build_pipeline(
        LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)
    ),
    'Random Forest': build_pipeline(
        RandomForestClassifier(class_weight='balanced', random_state=42, n_estimators=100)
    ),
     'Hist Gradient Boosting': build_pipeline(
        HistGradientBoostingClassifier(
            class_weight='balanced',
            random_state=42,
            max_iter=100
        )
    )
}

In [45]:
#Running perscision tests and confusion matrices on the 3 supervised models

all_results = {}
all_scores = {}
all_predictions = {}

for name, pipeline in models.items():
    print(f"\n{'='*50}")
    print(f"  {name}")
    print(f"{'='*50}")
    
    # Train
    pipeline.fit(X_train, y_train)
    
    # Predict
    y_pred = pipeline.predict(X_test)
    y_score = pipeline.predict_proba(X_test)[:, 1]
    # Results
    print(classification_report(y_test, y_pred, target_names=['Clean', 'Anomaly']))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))


    # Store model outputs
    all_scores[name] = y_score
    all_predictions[name] = y_pred

    # Build ranked results for this model
    results = X_test.copy()
    results['true_label'] = y_test.values
    results['predicted_label'] = y_pred
    results['anomaly_score'] = y_score

    results = results.sort_values('anomaly_score', ascending=False)

    all_results[name] = results

==================================================
  Logistic Regression
==================================================
              precision    recall  f1-score   support

       Clean       0.99      0.79      0.88      1248
     Anomaly       0.08      0.71      0.15        34

    accuracy                           0.79      1282
   macro avg       0.54      0.75      0.51      1282
weighted avg       0.97      0.79      0.86      1282

Confusion Matrix:
[[983 265]
 [ 10  24]]

==================================================
  Random Forest
==================================================
              precision    recall  f1-score   support

       Clean       0.99      0.99      0.99      1248
     Anomaly       0.62      0.47      0.53        34

    accuracy                           0.98      1282
   macro avg       0.80      0.73      0.76      1282
weighted avg       0.98      0.98      0.98      1282

Confusion Matrix:
[[1238   10]
 [  18   16]]

==================================================
  Hist Gradient Boosting
==================================================
              precision    recall  f1-score   support

       Clean       0.99      0.97      0.98      1248
     Anomaly       0.43      0.76      0.55        34

    accuracy                           0.97      1282
   macro avg       0.71      0.87      0.76      1282
weighted avg       0.98      0.97      0.97      1282

Confusion Matrix:
[[1213   35]
 [   8   26]]

In [46]:
all_results['Logistic Regression'].head(20)

,bw_lb,jump_height_cm,force_at_zero_vel,bw_change,jump_height_change,jump_height_change_per_day,bw_change_per_day,true_label,predicted_label,anomaly_score
412,41.3,0.000000,201.315741,-200.2,-42.475095,-14.158365,-66.733333,1,1,1.000000
3199,34.4,0.000000,19.723696,-101.4,-32.883265,-4.697609,-14.485714,1,1,0.999383
970,146.4,5.342916,1643.451336,-60.9,-30.904250,-30.904250,-60.900000,1,1,0.999003
984,146.5,7.430512,1491.908397,-60.0,-31.286080,-31.286080,-60.000000,1,1,0.998939
934,148.7,8.169300,1827.360039,-56.1,-24.614110,-24.614110,-56.100000,1,1,0.998172
3105,135.9,26.725499,1327.914480,-55.9,-7.592386,-3.796193,-27.950000,0,1,0.991365
991,144.2,6.355754,1676.330401,-98.6,0.609459,NaN,NaN,0,1,0.991221
955,148.5,5.418149,1779.605687,-97.7,-2.452379,NaN,NaN,0,1,0.990156
974,147.6,3.869468,1540.450287,-95.8,-6.601301,NaN,NaN,0,1,0.989905
851,198.6,21.768159,1624.508459,-44.6,14.201622,14.201622,-44.600000,0,1,0.989391
946,148.2,7.315344,1733.179298,-38.7,-1.510290,-1.510290,-38.700000,1,1,0.987384
1307,190.7,50.845699,2458.172233,-81.3,20.227210,2.889601,-11.614286,1,1,0.983020
814,202.0,17.171478,2310.552211,-40.8,-2.806999,-2.806999,-40.800000,0,1,0.980069
926,144.2,6.610558,1548.060725,-60.3,-24.611050,-4.922210,-12.060000,1,1,0.976588
1866,196.4,58.207985,2567.203095,-57.0,17.759687,5.919896,-19.000000,1,1,0.964918
450,183.0,69.582830,2900.917889,-66.4,23.014481,3.287783,-9.485714,1,1,0.961724
4278,145.0,61.010836,2325.455014,-50.3,11.273792,2.818448,-12.575000,1,1,0.960676
2567,191.1,46.122478,2187.917889,-64.7,14.142708,2.020387,-9.242857,1,1,0.959540
5657,185.6,53.148870,1653.693897,-68.2,22.597592,NaN,NaN,0,1,0.949173
1527,110.6,40.274171,1380.857539,-38.9,9.758457,1.219807,-4.862500,0,1,0.937474

In [71]:
#absolute coefficient importance (LR)
importances = pd.Series(
    abs(models['Logistic Regression']
        .named_steps['model']
        .coef_[0]),
    index=X_train.columns
).sort_values(ascending=False)

print(importances)

jump_height_cm                1.826593
bw_lb                         0.565593
bw_change                     0.505188
jump_height_change            0.192247
bw_change_per_day             0.191597
force_at_zero_vel             0.140754
jump_height_change_per_day    0.051576
dtype: float64

In [47]:
all_results['Random Forest'].head(20)

,bw_lb,jump_height_cm,force_at_zero_vel,bw_change,jump_height_change,jump_height_change_per_day,bw_change_per_day,true_label,predicted_label,anomaly_score
2567,191.1,46.122478,2187.917889,-64.7,14.142708,2.020387,-9.242857,1,1,0.99
1307,190.7,50.845699,2458.172233,-81.3,20.227210,2.889601,-11.614286,1,1,0.96
1866,196.4,58.207985,2567.203095,-57.0,17.759687,5.919896,-19.000000,1,1,0.91
11,178.2,56.533229,2411.467858,-38.6,13.699105,6.849552,-19.300000,1,1,0.91
4307,200.0,60.318608,2668.721707,-48.6,17.136823,4.284206,-12.150000,0,1,0.88
450,183.0,69.582830,2900.917889,-66.4,23.014481,3.287783,-9.485714,1,1,0.83
5280,205.1,44.195937,3040.651093,-23.9,5.397235,1.799078,-7.966667,1,1,0.82
4278,145.0,61.010836,2325.455014,-50.3,11.273792,2.818448,-12.575000,1,1,0.82
5148,141.4,30.022061,1586.297322,-15.9,5.670742,0.810106,-2.271429,0,1,0.81
162,173.7,41.412475,1782.588571,-23.3,9.246992,1.320999,-3.328571,1,1,0.77
851,198.6,21.768159,1624.508459,-44.6,14.201622,14.201622,-44.600000,0,1,0.75
1527,110.6,40.274171,1380.857539,-38.9,9.758457,1.219807,-4.862500,0,1,0.75
2229,172.1,51.854731,2262.899048,-23.4,9.131359,1.304480,-3.342857,1,1,0.72
820,200.7,26.629553,1849.114554,-42.6,-0.953319,-0.190664,-8.520000,0,1,0.69
870,200.4,14.801872,1598.543078,-42.6,8.472036,1.412006,-7.100000,1,1,0.66
3581,179.6,51.890481,2365.573403,-19.1,6.796705,0.970958,-2.728571,1,1,0.61
829,184.4,31.710311,1740.758553,-57.0,22.234399,NaN,NaN,0,1,0.57
3272,175.2,51.255112,2531.723562,-28.2,6.344550,0.126891,-0.564000,0,1,0.56
16,199.1,46.690065,2539.255238,-18.4,5.272294,0.753185,-2.628571,1,1,0.54
822,184.6,36.607038,1846.134766,-16.7,2.346496,2.346496,-16.700000,1,1,0.53

In [48]:
#feature importance (RF)

importances = pd.Series(
    models['Random Forest'].named_steps['model'].feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

print(importances)

bw_change                     0.379840
bw_change_per_day             0.214892
jump_height_change            0.131359
jump_height_change_per_day    0.079208
bw_lb                         0.071577
force_at_zero_vel             0.070924
jump_height_cm                0.052199
dtype: float64

In [49]:
# all_results['Hist Gradient Boosting'].head(20)
lr_low = all_results['Hist Gradient Boosting'][
    all_results['Hist Gradient Boosting']['predicted_label'] == 0
]

print(lr_low.head(40))

      bw_lb  jump_height_cm  force_at_zero_vel  bw_change  jump_height_change  \
2138  175.7       40.181394        1700.585185        0.7            4.200466
841   185.7       28.876839        1720.788201      -13.6           -4.736341
802   200.9       35.686611        2002.863231       17.9            6.269900
2002  183.5       51.790725        2043.129870       -8.3            9.717309
853   187.2       26.610450        1682.671647      -11.9           -0.021291
3076  139.4       29.074392        1525.529125        7.7            2.615655
930   130.8        3.849414        1389.917733      -14.7           -0.651249
3104  191.8       34.317885        2120.582769       55.1            3.592687
917   182.0       14.783405        1523.088126      -21.1          -24.483432
779   205.0       38.995512        2366.412512      -13.4            5.837964
992   183.6       33.997364        2186.003280       39.4           27.641611
843   200.3       35.914051        2092.216397       14.6           11.687405
458   226.2       43.470175        2835.128088      -16.9           -1.881624
965   173.3       12.812990        1455.215722      -10.9            8.084483
810   244.0       20.739613        2818.568646       59.9          -15.251132
3103  136.7       30.725198        1370.916102        3.3            0.311952
859   200.0       36.313736        2320.385496       16.4            0.107384
778   218.4       33.157548        1826.983301       10.2           -6.404710
3259  184.9       40.092822        2218.801035        0.3            6.556953
940   185.8       16.290805        1432.617135       38.2            0.976355
1692  132.0       30.688359        1637.382066        0.7           -0.005631
3227  174.2       42.391409        1975.874609        NaN                 NaN
819   243.3       27.582872        2561.952690       41.3           -5.866361
3088  135.5       27.573747        1441.173410       -6.3           -1.348645
1691  131.3       30.693990        1634.635255        0.5            0.060181
808   245.2       27.590371        2628.657895       61.3           -8.570150
3195  133.6       30.311486        1742.923440        0.4            2.550622
174   197.8       39.548784        2011.919476       -3.6           -3.513382
1707  136.3       28.860729        1591.216667        1.7            1.612905
1716  141.1       28.138845        1735.445197        7.7           -0.333090
423   245.4       45.231181        3110.145418        0.9            1.506398
956   245.8       10.768055        3412.040658       97.3            5.349906
1956  192.5       51.888283        2676.400000      -12.4            7.241000
1957  183.3       61.336288        2463.449177       -9.2            9.448005
185   202.1       43.501928        2253.440850       -0.1            3.176116
163   192.6       37.760051        1843.757406       18.9           -3.652424
896   194.5       50.386312        2223.927644       -9.1           17.686364
1703  134.8       28.943719        1702.349030        3.5            5.785321
3244  177.6       40.998849        2127.465165        0.9            6.363813
973   243.4       10.470770        2599.223310       95.7            5.828562

      jump_height_change_per_day  bw_change_per_day  true_label  \
2138                    0.600067           0.100000           0
841                    -4.736341         -13.600000           0
802                     3.134950           8.950000           0
2002                    2.429327          -2.075000           0
853                          NaN                NaN           0
3076                    0.145314           0.427778           0
930                          NaN                NaN           0
3104                         NaN                NaN           1
917                   -24.483432         -21.100000           0
779                     0.648663          -1.488889           0
992                          NaN                NaN           0
843                     5.843702           7.300000           0
458                    -0.110684          -0.994118           0
965                          NaN                NaN           0
810                          NaN                NaN           0
3103                    0.103984           1.100000           0
859                     0.026846           4.100000           0
778                    -1.067452           1.700000           0
3259                    0.936708           0.042857           0
940                          NaN                NaN           0
1692                   -0.000938           0.116667           0
3227                         NaN                NaN           0
819                          NaN                NaN           0
3088                   -0.009112          -0.042568           0
1691                    0.008597           0.071429           0
808                          NaN                NaN           0
3195                    0.510124           0.080000           0
174                    -0.021959          -0.022500           0
1707                    0.322581           0.340000           0
1716                   -0.001641           0.037931           0
423                     0.753199           0.450000           0
956                          NaN                NaN           0
1956                         NaN                NaN           0
1957                    4.724002          -4.600000           0
185                     0.453731          -0.014286           0
163                    -0.521775           2.700000           0
896                          NaN                NaN           0
1703                    0.120528           0.072917           0
3244                    3.181907           0.450000           0
973                          NaN                NaN           0

      predicted_label  anomaly_score
2138                0       0.489528
841                 0       0.476797
802                 0       0.398114
2002                0       0.384313
853                 0       0.371282
3076                0       0.332105
930                 0       0.313005
3104                0       0.307441
917                 0       0.260680
779                 0       0.249300
992                 0       0.203375
843                 0       0.158826
458                 0       0.155903
965                 0       0.149753
810                 0       0.133700
3103                0       0.118942
859                 0       0.096195
778                 0       0.079836
3259                0       0.069612
940                 0       0.067036
1692                0       0.065457
3227                0       0.064562
819                 0       0.061442
3088                0       0.060921
1691                0       0.059049
808                 0       0.058516
3195                0       0.052383
174                 0       0.045746
1707                0       0.041007
1716                0       0.038741
423                 0       0.036511
956                 0       0.035620
1956                0       0.031823
1957                0       0.031822
185                 0       0.030687
163                 0       0.028622
896                 0       0.027141
1703                0       0.026270
3244                0       0.024092
973                 0       0.023919

In [50]:
lr_low = all_results['Hist Gradient Boosting'][
    all_results['Hist Gradient Boosting']['predicted_label'] == 1
]

print(lr_low.head(40))

      bw_lb  jump_height_cm  force_at_zero_vel  bw_change  jump_height_change  \
2567  191.1       46.122478        2187.917889      -64.7           14.142708
450   183.0       69.582830        2900.917889      -66.4           23.014481
4278  145.0       61.010836        2325.455014      -50.3           11.273792
11    178.2       56.533229        2411.467858      -38.6           13.699105
1866  196.4       58.207985        2567.203095      -57.0           17.759687
1307  190.7       50.845699        2458.172233      -81.3           20.227210
851   198.6       21.768159        1624.508459      -44.6           14.201622
4307  200.0       60.318608        2668.721707      -48.6           17.136823
807   183.9       36.160521        1786.657895      -59.8           31.234036
809   184.1       35.990745        1802.313953      -61.1            8.400374
811   183.0       36.775369        1851.901979      -61.0           16.035756
835   198.5       40.119471        2183.515729      -43.4           32.346483
5657  185.6       53.148870        1653.693897      -68.2           22.597592
829   184.4       31.710311        1740.758553      -57.0           22.234399
910   195.3       29.916034        1628.863095      -44.9           23.770711
5280  205.1       44.195937        3040.651093      -23.9            5.397235
912   164.5       54.907745        1903.358013      -38.1           31.153955
818   202.0       33.449233        1998.001779      -42.2           31.112098
162   173.7       41.412475        1782.588571      -23.3            9.246992
870   200.4       14.801872        1598.543078      -42.6            8.472036
3199   34.4        0.000000          19.723696     -101.4          -32.883265
412    41.3        0.000000         201.315741     -200.2          -42.475095
2229  172.1       51.854731        2262.899048      -23.4            9.131359
906   184.3       33.376722        1553.658135      -18.3           11.644309
820   200.7       26.629553        1849.114554      -42.6           -0.953319
3272  175.2       51.255112        2531.723562      -28.2            6.344550
5148  141.4       30.022061        1586.297322      -15.9            5.670742
822   184.6       36.607038        1846.134766      -16.7            2.346496
3105  135.9       26.725499        1327.914480      -55.9           -7.592386
5219  225.4       32.308600        2671.860771      -24.7            3.804746
427   225.0       46.880410        3103.255238      -19.0            3.989295
2102  139.3       32.351855        1654.519350       14.5            5.998406
496   176.4       39.232450        2303.448479      -16.6            2.875953
3581  179.6       51.890481        2365.573403      -19.1            6.796705
3514  147.9       32.917967        1605.026710       21.8            9.003427
2103  123.5       27.617142        1476.706273      -15.8           -4.734713
1527  110.6       40.274171        1380.857539      -38.9            9.758457
16    199.1       46.690065        2539.255238      -18.4            5.272294
975   183.9        9.252123        1242.159574       36.3            5.382655
4941  152.8       28.429399        1608.090271       12.1            0.882643

      jump_height_change_per_day  bw_change_per_day  true_label  \
2567                    2.020387          -9.242857           1
450                     3.287783          -9.485714           1
4278                    2.818448         -12.575000           1
11                      6.849552         -19.300000           1
1866                    5.919896         -19.000000           1
1307                    2.889601         -11.614286           1
851                    14.201622         -44.600000           0
4307                    4.284206         -12.150000           0
807                          NaN                NaN           0
809                          NaN                NaN           0
811                          NaN                NaN           0
835                          NaN                NaN           0
5657                         NaN                NaN           0
829                          NaN                NaN           0
910                          NaN                NaN           0
5280                    1.799078          -7.966667           1
912                          NaN                NaN           0
818                          NaN                NaN           0
162                     1.320999          -3.328571           1
870                     1.412006          -7.100000           1
3199                   -4.697609         -14.485714           1
412                   -14.158365         -66.733333           1
2229                    1.304480          -3.342857           1
906                    11.644309         -18.300000           1
820                    -0.190664          -8.520000           0
3272                    0.126891          -0.564000           0
5148                    0.810106          -2.271429           0
822                     2.346496         -16.700000           1
3105                   -3.796193         -27.950000           0
5219                         NaN                NaN           0
427                     0.569899          -2.714286           0
2102                    0.999734           2.416667           1
496                     1.437977          -8.300000           1
3581                    0.970958          -2.728571           1
3514                         NaN                NaN           0
2103                   -4.734713         -15.800000           0
1527                    1.219807          -4.862500           0
16                      0.753185          -2.628571           1
975                          NaN                NaN           0
4941                    0.126092           1.728571           1

      predicted_label  anomaly_score
2567                1       0.999854
450                 1       0.999845
4278                1       0.999835
11                  1       0.999824
1866                1       0.999815
1307                1       0.999815
851                 1       0.999799
4307                1       0.999767
807                 1       0.999755
809                 1       0.999755
811                 1       0.999734
835                 1       0.999634
5657                1       0.999558
829                 1       0.999555
910                 1       0.999510
5280                1       0.999509
912                 1       0.999448
818                 1       0.999208
162                 1       0.998756
870                 1       0.998302
3199                1       0.997502
412                 1       0.997502
2229                1       0.997257
906                 1       0.996943
820                 1       0.996035
3272                1       0.994626
5148                1       0.993363
822                 1       0.991365
3105                1       0.987710
5219                1       0.980350
427                 1       0.976077
2102                1       0.963028
496                 1       0.962910
3581                1       0.936172
3514                1       0.935787
2103                1       0.923525
1527                1       0.920026
16                  1       0.918037
975                 1       0.915279
4941                1       0.884786

In [70]:
#permutation_importance (HGB)
perm = permutation_importance(
    models['Hist Gradient Boosting'],
    X_test,
    y_test,
    n_repeats=10,
    random_state=42
)

importances = pd.Series(
    perm.importances_mean,
    index=X_train.columns
).sort_values(ascending=False)

print(importances)

bw_change                     0.038612
jump_height_cm                0.005616
bw_lb                         0.002106
force_at_zero_vel             0.001950
bw_change_per_day             0.001482
jump_height_change_per_day    0.000624
jump_height_change           -0.000390
dtype: float64

In [51]:
# isolation forest for 

print(f"\n{'='*50}")
print(f"  Isolation Forest")
print(f"{'='*50}")

contamination = y_train.sum() / len(y_train)
print(f"Contamination rate: {contamination:.4f}")

iso_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
    ('model', IsolationForest(
        contamination=contamination,
        random_state=42,
        n_estimators=100
    ))
])

iso_pipeline.fit(X_train)

y_pred_iso = iso_pipeline.predict(X_test)
y_pred_iso = np.where(y_pred_iso == -1, 1, 0)

iso_raw_score = -iso_pipeline.decision_function(X_test)

iso_score = (iso_raw_score - iso_raw_score.min()) / (iso_raw_score.max() - iso_raw_score.min())

print(classification_report(y_test, y_pred_iso, target_names=['Clean', 'Anomaly']))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_iso))

iso_results = X_test.copy()
iso_results['true_label'] = y_test.values
iso_results['predicted_label'] = y_pred_iso
iso_results['anomaly_score'] = iso_score
iso_results = iso_results.sort_values('anomaly_score', ascending=False)

all_results['Isolation Forest'] = iso_results
all_scores['Isolation Forest'] = iso_score
all_predictions['Isolation Forest'] = y_pred_iso

==================================================
  Isolation Forest
==================================================
Contamination rate: 0.0242
              precision    recall  f1-score   support

       Clean       0.99      0.96      0.98      1248
     Anomaly       0.31      0.62      0.41        34

    accuracy                           0.95      1282
   macro avg       0.65      0.79      0.69      1282
weighted avg       0.97      0.95      0.96      1282

Confusion Matrix:
[[1201   47]
 [  13   21]]

In [52]:
all_results['Isolation Forest'].head(20)

,bw_lb,jump_height_cm,force_at_zero_vel,bw_change,jump_height_change,jump_height_change_per_day,bw_change_per_day,true_label,predicted_label,anomaly_score
412,41.3,0.000000,201.315741,-200.2,-42.475095,-14.158365,-66.733333,1,1,1.000000
3199,34.4,0.000000,19.723696,-101.4,-32.883265,-4.697609,-14.485714,1,1,0.960119
867,243.9,7.623854,3186.821123,46.6,-19.848081,-19.848081,46.600000,0,1,0.943959
847,242.6,12.132906,3484.065863,41.9,-25.610332,-25.610332,41.900000,0,1,0.938048
984,146.5,7.430512,1491.908397,-60.0,-31.286080,-31.286080,-60.000000,1,1,0.929599
954,246.2,7.870528,3030.668979,37.6,-24.121800,-24.121800,37.600000,0,1,0.929563
970,146.4,5.342916,1643.451336,-60.9,-30.904250,-30.904250,-60.900000,1,1,0.928934
806,243.7,4.926485,2918.712717,42.9,-31.761333,-31.761333,42.900000,0,1,0.928231
934,148.7,8.169300,1827.360039,-56.1,-24.614110,-24.614110,-56.100000,1,1,0.926971
1866,196.4,58.207985,2567.203095,-57.0,17.759687,5.919896,-19.000000,1,1,0.902948
851,198.6,21.768159,1624.508459,-44.6,14.201622,14.201622,-44.600000,0,1,0.896261
450,183.0,69.582830,2900.917889,-66.4,23.014481,3.287783,-9.485714,1,1,0.895314
917,182.0,14.783405,1523.088126,-21.1,-24.483432,-24.483432,-21.100000,0,1,0.879716
413,242.8,41.558378,3021.875000,201.5,41.558378,20.779189,100.750000,0,1,0.877749
11,178.2,56.533229,2411.467858,-38.6,13.699105,6.849552,-19.300000,1,1,0.873952
1307,190.7,50.845699,2458.172233,-81.3,20.227210,2.889601,-11.614286,1,1,0.871974
4307,200.0,60.318608,2668.721707,-48.6,17.136823,4.284206,-12.150000,0,1,0.871963
913,205.0,24.351791,2019.186069,40.5,-30.555955,-30.555955,40.500000,0,1,0.864802
4278,145.0,61.010836,2325.455014,-50.3,11.273792,2.818448,-12.575000,1,1,0.863052
926,144.2,6.610558,1548.060725,-60.3,-24.611050,-4.922210,-12.060000,1,1,0.848370

In [53]:
comparison = X_test.copy()
comparison['true_label'] = y_test.values

for name in all_scores:
    comparison[f'{name}_score'] = all_scores[name]
    comparison[f'{name}_pred'] = all_predictions[name]

comparison.sort_values('Hist Gradient Boosting_score', ascending=False).head(50)

,bw_lb,jump_height_cm,force_at_zero_vel,bw_change,jump_height_change,jump_height_change_per_day,bw_change_per_day,true_label,Logistic Regression_score,Logistic Regression_pred,Random Forest_score,Random Forest_pred,Hist Gradient Boosting_score,Hist Gradient Boosting_pred,Isolation Forest_score,Isolation Forest_pred
2567,191.1,46.122478,2187.917889,-64.7,14.142708,2.020387,-9.242857,1,0.959540,1,0.99,1,0.999854,1,0.756871,1
450,183.0,69.582830,2900.917889,-66.4,23.014481,3.287783,-9.485714,1,0.961724,1,0.83,1,0.999845,1,0.895314,1
4278,145.0,61.010836,2325.455014,-50.3,11.273792,2.818448,-12.575000,1,0.960676,1,0.82,1,0.999835,1,0.863052,1
11,178.2,56.533229,2411.467858,-38.6,13.699105,6.849552,-19.300000,1,0.936501,1,0.91,1,0.999824,1,0.873952,1
1866,196.4,58.207985,2567.203095,-57.0,17.759687,5.919896,-19.000000,1,0.964918,1,0.91,1,0.999815,1,0.902948,1
1307,190.7,50.845699,2458.172233,-81.3,20.227210,2.889601,-11.614286,1,0.983020,1,0.96,1,0.999815,1,0.871974,1
851,198.6,21.768159,1624.508459,-44.6,14.201622,14.201622,-44.600000,0,0.989391,1,0.75,1,0.999799,1,0.896261,1
4307,200.0,60.318608,2668.721707,-48.6,17.136823,4.284206,-12.150000,0,0.917333,1,0.88,1,0.999767,1,0.871963,1
807,183.9,36.160521,1786.657895,-59.8,31.234036,NaN,NaN,0,0.922683,1,0.52,1,0.999755,1,0.540229,0
809,184.1,35.990745,1802.313953,-61.1,8.400374,NaN,NaN,0,0.926781,1,0.51,1,0.999755,1,0.414654,0
811,183.0,36.775369,1851.901979,-61.0,16.035756,NaN,NaN,0,0.926484,1,0.50,0,0.999734,1,0.531039,0
835,198.5,40.119471,2183.515729,-43.4,32.346483,NaN,NaN,0,0.810529,1,0.43,0,0.999634,1,0.523121,0
5657,185.6,53.148870,1653.693897,-68.2,22.597592,NaN,NaN,0,0.949173,1,0.50,0,0.999558,1,0.605751,1
829,184.4,31.710311,1740.758553,-57.0,22.234399,NaN,NaN,0,0.912490,1,0.57,1,0.999555,1,0.519043,0
910,195.3,29.916034,1628.863095,-44.9,23.770711,NaN,NaN,0,0.842137,1,0.52,1,0.999510,1,0.532751,0
5280,205.1,44.195937,3040.651093,-23.9,5.397235,1.799078,-7.966667,1,0.686295,1,0.82,1,0.999509,1,0.617280,1
912,164.5,54.907745,1903.358013,-38.1,31.153955,NaN,NaN,0,0.841106,1,0.48,0,0.999448,1,0.599950,1
818,202.0,33.449233,1998.001779,-42.2,31.112098,NaN,NaN,0,0.800626,1,0.49,0,0.999208,1,0.528746,0
162,173.7,41.412475,1782.588571,-23.3,9.246992,1.320999,-3.328571,1,0.747897,1,0.77,1,0.998756,1,0.531520,0
870,200.4,14.801872,1598.543078,-42.6,8.472036,1.412006,-7.100000,1,0.876010,1,0.66,1,0.998302,1,0.737020,1
3199,34.4,0.000000,19.723696,-101.4,-32.883265,-4.697609,-14.485714,1,0.999383,1,0.33,0,0.997502,1,0.960119,1
412,41.3,0.000000,201.315741,-200.2,-42.475095,-14.158365,-66.733333,1,1.000000,1,0.34,0,0.997502,1,1.000000,1
2229,172.1,51.854731,2262.899048,-23.4,9.131359,1.304480,-3.342857,1,0.734060,1,0.72,1,0.997257,1,0.550196,1
906,184.3,33.376722,1553.658135,-18.3,11.644309,11.644309,-18.300000,1,0.852714,1,0.52,1,0.996943,1,0.772903,1
820,200.7,26.629553,1849.114554,-42.6,-0.953319,-0.190664,-8.520000,0,0.881756,1,0.69,1,0.996035,1,0.495670,0
3272,175.2,51.255112,2531.723562,-28.2,6.344550,0.126891,-0.564000,0,0.723564,1,0.56,1,0.994626,1,0.384344,0
5148,141.4,30.022061,1586.297322,-15.9,5.670742,0.810106,-2.271429,0,0.739122,1,0.81,1,0.993363,1,0.376549,0
822,184.6,36.607038,1846.134766,-16.7,2.346496,2.346496,-16.700000,1,0.818800,1,0.53,1,0.991365,1,0.571950,1
3105,135.9,26.725499,1327.914480,-55.9,-7.592386,-3.796193,-27.950000,0,0.991365,1,0.40,0,0.987710,1,0.813233,1
5219,225.4,32.308600,2671.860771,-24.7,3.804746,NaN,NaN,0,0.535953,1,0.28,0,0.980350,1,0.280491,0
427,225.0,46.880410,3103.255238,-19.0,3.989295,0.569899,-2.714286,0,0.495098,0,0.28,0,0.976077,1,0.445666,0
2102,139.3,32.351855,1654.519350,14.5,5.998406,0.999734,2.416667,1,0.331702,0,0.21,0,0.963028,1,0.365075,0
496,176.4,39.232450,2303.448479,-16.6,2.875953,1.437977,-8.300000,1,0.718409,1,0.51,1,0.962910,1,0.467860,0
3581,179.6,51.890481,2365.573403,-19.1,6.796705,0.970958,-2.728571,1,0.660385,1,0.61,1,0.936172,1,0.444281,0
3514,147.9,32.917967,1605.026710,21.8,9.003427,NaN,NaN,0,0.274842,0,0.36,0,0.935787,1,0.312367,0
2103,123.5,27.617142,1476.706273,-15.8,-4.734713,-4.734713,-15.800000,0,0.894716,1,0.36,0,0.923525,1,0.716900,1
1527,110.6,40.274171,1380.857539,-38.9,9.758457,1.219807,-4.862500,0,0.937474,1,0.75,1,0.920026,1,0.658767,1
16,199.1,46.690065,2539.255238,-18.4,5.272294,0.753185,-2.628571,1,0.589546,1,0.54,1,0.918037,1,0.337352,0
975,183.9,9.252123,1242.159574,36.3,5.382655,NaN,NaN,0,0.118340,0,0.25,0,0.915279,1,0.421038,0
4941,152.8,28.429399,1608.090271,12.1,0.882643,0.126092,1.728571,1,0.335510,0,0.28,0,0.884786,1,0.221434,0
877,185.2,24.692008,1455.350598,-14.3,-10.729259,-10.729259,-14.300000,0,0.786117,1,0.22,0,0.850677,1,0.766263,1
957,184.4,14.533335,1393.864603,-61.4,3.765280,NaN,NaN,0,0.931252,1,0.34,0,0.838719,1,0.445549,0
898,194.5,32.548899,2077.075533,-8.1,-5.698553,NaN,NaN,0,0.458733,0,0.33,0,0.835522,1,0.116678,0
942,185.4,24.639684,1433.440222,37.1,15.280013,NaN,NaN,0,0.111081,0,0.24,0,0.815145,1,0.483291,0
1723,129.3,33.664936,1473.962620,-9.1,6.314553,0.451039,-0.650000,1,0.685026,1,0.37,0,0.809334,1,0.266196,0
974,147.6,3.869468,1540.450287,-95.8,-6.601301,NaN,NaN,0,0.989905,1,0.44,0,0.804200,1,0.551680,1
790,187.3,22.636427,1520.417053,-16.6,-11.858568,-11.858568,-16.600000,0,0.820446,1,0.25,0,0.780861,1,0.810976,1
941,148.3,9.359671,1992.290099,-37.5,-6.931134,NaN,NaN,0,0.846550,1,0.41,0,0.775208,1,0.490555,0
3515,126.1,24.566614,1487.301921,-21.8,-8.351353,-1.193050,-3.114286,1,0.826047,1,0.36,0,0.768761,1,0.603575,1
970,146.4,5.342916,1643.451336,-60.9,-30.904250,-30.904250,-60.900000,1,0.999003,1,0.31,0,0.755736,1,0.928934,1

In [54]:
anom = test_train_data[
    test_train_data['is_anomaly'] == 0
]

cols = [
    'bw_lb', 
    'jump_height_cm', 
    'force_at_zero_vel', 
    'bw_change', 
    'jump_height_change', 
    'jump_height_change_per_day', 
    'bw_change_per_day', 
    
]

anom[cols].describe()

,bw_lb,jump_height_cm,force_at_zero_vel,bw_change,jump_height_change,jump_height_change_per_day,bw_change_per_day
count,5639.000000,5641.000000,5641.000000,5517.000000,5521.000000,5143.000000,5139.000000
mean,206.515730,34.889492,2221.982684,0.778684,-14.868192,-6.157025,0.203276
std,50.302945,8.888346,574.531937,9.719598,836.925091,316.136471,3.223568
min,110.600000,1.839345,973.917733,-98.600000,-57098.325432,-19032.775144,-44.600000
25%,171.200000,28.516827,1740.448145,-1.400000,-1.504699,-0.213404,-0.209127
50%,200.500000,34.488020,2211.835753,0.100000,0.010197,-0.000430,0.014286
75%,239.350000,40.652274,2630.276908,1.600000,1.544649,0.210343,0.242857
max,390.500000,87.815260,4368.656015,201.500000,62.794824,20.779189,100.750000

In [55]:
modelling_data['bw_change_per_day'] = modelling_data['bw_change_per_day'].replace([np.inf, -np.inf], np.nan)

print(f"Athletes in prediction set: {modelling_data['name'].nunique()}")
print(f"Total rows: {len(modelling_data)}")

Athletes in prediction set: 714
Total rows: 17621

In [56]:
# prediction_meta = modelling_data[['name', 'date', 'set']].copy()
# # Step 1: Drop identifier columns from prediction data
# # Keep name and date so you can report back to S&C staff

# drop_cols = ['name', 'date', 'datetime', 'sport', 'set', 'days_since_last_test']
# pred_df = modelling_data.drop(columns=drop_cols, errors='ignore')

# # Step 2: Make sure columns match training exactly
# # Drop is_anomaly if it exists
# if 'is_anomaly' in pred_df.columns:
#     pred_df = pred_df.drop(columns=['is_anomaly'])

# # Confirm columns match
# print("Training columns:", X_train.columns.tolist())
# print("Prediction columns:", pred_df.columns.tolist())
# print("Match:", X_train.columns.tolist() == pred_df.columns.tolist())

# # Step 3: Get predictions and scores from all 3 supervised models
# # prediction_meta['LR_score']  = models['Logistic Regression'].predict_proba(pred_df)[:, 1]
# # prediction_meta['LR_pred']   = models['Logistic Regression'].predict(pred_df)

# prediction_meta['RF_score']  = models['Random Forest'].predict_proba(pred_df)[:, 1]
# prediction_meta['RF_pred']   = models['Random Forest'].predict(pred_df)

# prediction_meta['HGB_score'] = models['Hist Gradient Boosting'].predict_proba(pred_df)[:, 1]
# prediction_meta['HGB_pred']  = models['Hist Gradient Boosting'].predict(pred_df)

# prediction_meta['IF_score'] = models['Isolation Forest'].predict_proba(pred_df)[:, 1]
# prediction_meta['IF_pred']  = models['Isolation Forest'].predict(pred_df)

# # Step 4: Ensemble logic
# prediction_meta['models_agreed'] = (
#     prediction_meta['LR_pred'] +
#     prediction_meta['RF_pred'] +
#     prediction_meta['HGB_pred']
# )

# # High confidence = all 3 agree it's an anomaly
# prediction_meta['high_confidence'] = (
#     prediction_meta['models_agreed'] == 2
# ).astype(int)

# # Review needed = at least 2 of 3 agree
# prediction_meta['review_needed'] = (
#     prediction_meta['models_agreed'] >= 2
# ).astype(int)

# # Step 5: Summary
# print(f"\nTotal rows predicted: {len(prediction_meta)}")
# print(f"High confidence anomalies (all 3 agree): {prediction_meta['high_confidence'].sum()}")
# print(f"Review needed (2+ models agree): {prediction_meta['review_needed'].sum()}")

# # Step 6: Show high confidence flags first
# high_conf = prediction_meta[prediction_meta['high_confidence'] == 1].sort_values('HGB_score', ascending=False)
# print(f"\nHigh confidence anomalies:")
# print(high_conf[['name', 'date', 'set', 'HGB_score', 'RF_score']].to_string())

In [57]:
prediction_meta = modelling_data[['name', 'date', 'set', 'bw_change', 'jump_height_change', 'bw_change_per_day','days_since_last_test']].copy()

# Drop identifier columns
drop_cols = ['name', 'date', 'datetime', 'sport', 'set', 'days_since_last_test']
pred_df = modelling_data.drop(columns=drop_cols, errors='ignore')

# Drop is_anomaly if it exists
if 'is_anomaly' in pred_df.columns:
    pred_df = pred_df.drop(columns=['is_anomaly'])

# Replace infinity values
pred_df = pred_df.replace([np.inf, -np.inf], np.nan)

# Confirm columns match
print("Training columns:", X_train.columns.tolist())
print("Prediction columns:", pred_df.columns.tolist())
print("Match:", X_train.columns.tolist() == pred_df.columns.tolist())

# Random Forest and HGB — use predict_proba
prediction_meta['RF_score']  = models['Random Forest'].predict_proba(pred_df)[:, 1]
prediction_meta['RF_pred']   = models['Random Forest'].predict(pred_df)

prediction_meta['HGB_score'] = models['Hist Gradient Boosting'].predict_proba(pred_df)[:, 1]
prediction_meta['HGB_pred']  = models['Hist Gradient Boosting'].predict(pred_df)

# Isolation Forest — uses decision_function, not predict_proba
# Need to manually impute and scale since it wasn't in the pipeline
imputer = SimpleImputer(strategy='median')
scaler  = StandardScaler()

# Fit on training data then transform prediction data
X_train_iso = imputer.fit_transform(X_train)
X_pred_iso  = imputer.transform(pred_df)

X_train_iso = scaler.fit_transform(X_train_iso)
X_pred_iso  = scaler.transform(X_pred_iso)

# Fit Isolation Forest
iso = IsolationForest(
    contamination=y_train.sum() / len(y_train),
    random_state=42,
    n_estimators=100
)
iso.fit(X_train_iso)

# Get scores — more negative = more anomalous
# Normalize to 0-1 where higher = more anomalous
iso_raw_scores = iso.decision_function(X_pred_iso)
iso_scores_normalized = 1 - (
    (iso_raw_scores - iso_raw_scores.min()) / 
    (iso_raw_scores.max() - iso_raw_scores.min())
)

# Predict — convert -1 (anomaly) to 1, 1 (clean) to 0
iso_pred = np.where(iso.predict(X_pred_iso) == -1, 1, 0)

prediction_meta['ISO_score'] = iso_scores_normalized
prediction_meta['ISO_pred']  = iso_pred

# Ensemble — now using 3 models (RF, HGB, ISO)
prediction_meta['models_agreed'] = (
    prediction_meta['RF_pred'] +
    prediction_meta['HGB_pred'] +
    prediction_meta['ISO_pred']
)

# High confidence = all 3 agree
prediction_meta['high_confidence'] = (
    prediction_meta['models_agreed'] >= 3
).astype(int)

# Review needed = specifically HGB and ISO agree
prediction_meta['review_needed'] = (
    (prediction_meta['HGB_pred'] == 1) &
    (prediction_meta['ISO_pred'] == 1)
).astype(int)

# HGB only — fallback if no agreement between models
prediction_meta['hgb_only'] = (
    (prediction_meta['HGB_pred'] == 1) &
    (prediction_meta['ISO_pred'] == 0) &
    (prediction_meta['RF_pred'] == 0)
).astype(int)

# Summary
print(f"\nTotal rows predicted: {len(prediction_meta)}")
print(f"High confidence (all 3 agree): {prediction_meta['high_confidence'].sum()}")
print(f"Review needed (HGB + ISO agree): {prediction_meta['review_needed'].sum()}")
print(f"HGB only flags: {prediction_meta['hgb_only'].sum()}")

# Tiered if statement
high_conf = prediction_meta[
    prediction_meta['high_confidence'] == 1
].sort_values('HGB_score', ascending=False)

if len(high_conf) > 0:
    print(f"\nHigh confidence anomalies found: {len(high_conf)}")

else:
    high_conf = prediction_meta[
        prediction_meta['review_needed'] == 1
    ].sort_values('HGB_score', ascending=False)

    if len(high_conf) > 0:
        print(f"\nNo high confidence found — showing HGB + ISO agreement: {len(high_conf)}")

    else:
        high_conf = prediction_meta[
            prediction_meta['hgb_only'] == 1
        ].sort_values('HGB_score', ascending=False)
        print(f"\nNo model agreement — showing HGB only flags: {len(high_conf)}")

print(high_conf[['name', 'date', 'set', 'bw_change', 'jump_height_change',
                  'days_since_last_test', 'HGB_score', 'RF_score', 'ISO_score']].to_string())

Training columns: ['bw_lb', 'jump_height_cm', 'force_at_zero_vel', 'bw_change', 'jump_height_change', 'jump_height_change_per_day', 'bw_change_per_day']
Prediction columns: ['bw_lb', 'jump_height_cm', 'force_at_zero_vel', 'bw_change', 'jump_height_change', 'jump_height_change_per_day', 'bw_change_per_day']
Match: True

Total rows predicted: 17621
High confidence (all 3 agree): 1
Review needed (HGB + ISO agree): 1
HGB only flags: 49

High confidence anomalies found: 1
               name        date  set  bw_change  jump_height_change  days_since_last_test  HGB_score  RF_score  ISO_score
6264  eli goldstein  2025-05-28    1      -22.2           15.611345                  37.0    0.75252      0.53   0.794084

In [58]:
new_labels = high_conf[['name', 'date', 'set']].copy()
new_labels['is_anomaly'] = 1


d3_updated = pd.concat([d3, new_labels], ignore_index=True).drop_duplicates(
    subset=['name', 'date', 'set']
)


print(f"Original d3 anomalies: {d3['is_anomaly'].sum()}")
print(f"New anomalies added: {len(new_labels)}")
print(f"Updated d3 total: {d3_updated['is_anomaly'].sum()}")

Original d3 anomalies: 148
New anomalies added: 1
Updated d3 total: 149

In [59]:
# d3_updated.to_csv('cleaned_data/d3_updated.csv', index=False)
# print("d3_updated saved successfully")

In [63]:
full_assumed = fulld1.copy()

full_assumed = full_assumed.rename(columns={'is_anomaly': 'staff_indicated_anomaly'})

print(f"Total rows: {len(full_assumed)}")
print(f"Unique athletes: {full_assumed['name'].nunique()}")
print(f"Staff indicated anomalies: {full_assumed['staff_indicated_anomaly'].sum()}")

full_assumed['bw_change_per_day'] = full_assumed['bw_change_per_day'].replace(
    [np.inf, -np.inf], np.nan
)
full_assumed['jump_height_change_per_day'] = full_assumed['jump_height_change_per_day'].replace(
    [np.inf, -np.inf], np.nan
)

# Keep meta for reporting — include staff_indicated_anomaly
full_meta = full_assumed[['name', 'date', 'set', 'bw_lb',
                           'jump_height_cm', 'force_at_zero_vel',
                           'bw_change', 'bw_change_per_day',
                           'jump_height_change', 'jump_height_change_per_day',
                           'days_since_last_test',
                           'staff_indicated_anomaly']].copy()

drop_cols = ['name', 'date', 'datetime', 'sport', 'set',
             'days_since_last_test', 'staff_indicated_anomaly']
full_pred_df = full_assumed.drop(columns=drop_cols, errors='ignore')

full_pred_df = full_pred_df.replace([np.inf, -np.inf], np.nan)

print("\nMatch:", X_train.columns.tolist() == full_pred_df.columns.tolist())

full_meta['HGB_score'] = models['Hist Gradient Boosting'].predict_proba(full_pred_df)[:, 1]
full_meta['HGB_pred']  = models['Hist Gradient Boosting'].predict(full_pred_df)

imputer_full = SimpleImputer(strategy='median')
scaler_full  = StandardScaler()

X_train_iso_full = imputer_full.fit_transform(X_train)
X_pred_iso_full  = imputer_full.transform(full_pred_df)

X_train_iso_full = scaler_full.fit_transform(X_train_iso_full)
X_pred_iso_full  = scaler_full.transform(X_pred_iso_full)

iso_full = IsolationForest(
    contamination=y_train.sum() / len(y_train),
    random_state=42,
    n_estimators=100
)
iso_full.fit(X_train_iso_full)

iso_raw_full = iso_full.decision_function(X_pred_iso_full)
iso_scores_full = 1 - (
    (iso_raw_full - iso_raw_full.min()) /
    (iso_raw_full.max() - iso_raw_full.min())
)

full_meta['ISO_score'] = iso_scores_full
full_meta['ISO_pred']  = np.where(iso_full.predict(X_pred_iso_full) == -1, 1, 0)

full_meta['model_indicated_anomaly'] = (
    (full_meta['HGB_pred'] == 1) &
    (full_meta['ISO_pred'] == 1)
).astype(int)

print(f"\nTotal rows predicted: {len(full_meta)}")
print(f"Staff indicated anomalies: {full_meta['staff_indicated_anomaly'].sum()}")
print(f"Model indicated anomalies (HGB + ISO): {full_meta['model_indicated_anomaly'].sum()}")

indicated = full_meta[
    full_meta['model_indicated_anomaly'] == 1
].sort_values('HGB_score', ascending=False)

print(f"\nModel indicated anomalies:")
print(indicated[['name', 'date', 'bw_lb', 'jump_height_cm',
                  'bw_change', 'bw_change_per_day',
                  'jump_height_change', 'jump_height_change_per_day',
                  'days_since_last_test', 'HGB_score', 'ISO_score',
                  'HGB_pred', 'ISO_pred',
                  'staff_indicated_anomaly']].to_string())

full_meta.to_csv('cleaned_data/full_prediction_dataset', index=False)


#print("\nResults saved to cleaned_data/full_dataset_indicated_anomalies.csv")

Total rows: 23405
Unique athletes: 835
Staff indicated anomalies: 0

Match: True

Total rows predicted: 23405
Staff indicated anomalies: 0
Model indicated anomalies (HGB + ISO): 71

Model indicated anomalies:
                      name        date  bw_lb  jump_height_cm  bw_change  bw_change_per_day  jump_height_change  jump_height_change_per_day  days_since_last_test  HGB_score  ISO_score  HGB_pred  ISO_pred  staff_indicated_anomaly
19239    roland waguespack  2024-01-25  194.4       53.180178      -78.9         -11.271429           19.347495                    2.763928                   7.0   0.999856   0.847191         1         1                        0
20300          sean harmon  2024-01-25  178.7       56.457134      -76.5         -10.928571           20.670539                    2.952934                   7.0   0.999856   0.853197         1         1                        0
11734       joshua johnson  2024-05-08  215.1       48.713510      -38.4         -19.200000           13.904146                    6.952073                   2.0   0.999856   0.802771         1         1                        0
11762       joshua johnson  2025-07-15  191.4       59.302559      -62.5          -8.928571           18.404861                    2.629266                   7.0   0.999856   0.810999         1         1                        0
14792         marco dzamba  2026-03-09  180.0       42.774907      -39.1          -7.820000            8.774746                    1.754949                   5.0   0.999854   0.607345         1         1                        0
10796      joe onuwabhagbe  2025-07-15  191.1       46.122478      -64.7          -9.242857           14.142708                    2.020387                   7.0   0.999854   0.722731         1         1                        0
13249         khari mayeux  2025-07-15  206.2       43.586595      -63.8          -9.114286           11.919488                    1.702784                   7.0   0.999854   0.684030         1         1                        0
10977          john prince  2025-07-15  201.9       39.697365      -65.3          -9.328571           10.729769                    1.532824                   7.0   0.999854   0.659622         1         1                        0
7664   francisco caballero  2025-07-15  238.4       38.543306      -67.2          -9.600000           10.032391                    1.433199                   7.0   0.999852   0.678779         1         1                        0
2713        bruce williams  2025-07-15  183.0       69.582830      -66.4          -9.485714           23.014481                    3.287783                   7.0   0.999845   0.853645         1         1                        0
17215      niquis ratcliff  2025-11-02  145.0       61.010836      -50.3         -12.575000           11.273792                    2.818448                   4.0   0.999835   0.823138         1         1                        0
309          ahmir braxton  2024-05-08  139.3       45.094530      -40.4         -20.200000           12.804944                    6.402472                   2.0   0.999835   0.825809         1         1                        0
21549     taysire williams  2024-01-25  150.1       58.145684      -80.1          -5.721429           23.807146                    1.700510                  14.0   0.999833   0.826916         1         1                        0
18331     patrick campbell  2025-10-26  156.9       52.247903      -40.5          -8.100000            9.365248                    1.873050                   5.0   0.999833   0.670491         1         1                        0
12        abayomi babalola  2024-05-08  178.2       56.533229      -38.6         -19.300000           13.699105                    6.849552                   2.0   0.999824   0.833445         1         1                        0
5723         delby lemieux  2024-01-25  190.7       50.845699      -81.3         -11.614286           20.227210                    2.889601                   7.0   0.999815   0.831574         1         1                        0
7863         gergely hudak  2025-09-24  196.4       58.207985      -57.0         -19.000000           17.759687                    5.919896                   3.0   0.999815   0.860864         1         1                        0
7620   francisco caballero  2024-01-25  198.0       41.807520      -87.3         -12.471429           15.282248                    2.183178                   7.0   0.999815   0.809539         1         1                        0
4129         chase engdahl  2025-10-17  198.6       21.768159      -44.6         -44.600000           14.201622                   14.201622                   1.0   0.999799   0.854541         1         1                        0
3699         carson franks  2024-04-19    2.3    57144.084579     -198.5         -99.250000        57098.409250                28549.204625                   2.0   0.999783   1.000000         1         1                        0
17811         olivia lyman  2026-03-02    2.7    24670.235576     -170.8         -24.400000        24644.342226                 3520.620318                   7.0   0.999783   1.000000         1         1                        0
5057         conor mcnally  2025-06-28  204.6       20.841644     -123.7          -5.622727           18.004707                    0.818396                  22.0   0.999782   0.770639         1         1                        0
7928          godson ajoku  2024-01-25  243.3       46.607033      -78.9         -11.271429           15.711314                    2.244473                   7.0   0.999767   0.829826         1         1                        0
17244        no'koi maddox  2025-09-28  200.0       60.318608      -48.6         -12.150000           17.136823                    4.284206                   4.0   0.999767   0.831564         1         1                        0
19291    roland waguespack  2025-07-15  213.8       54.837693      -66.7          -9.528571           16.655911                    2.379416                   7.0   0.999767   0.810701         1         1                        0
13321     konstantin spork  2024-01-25  215.2       40.165530      -82.3         -11.757143           14.064192                    2.009170                   7.0   0.999728   0.788997         1         1                        0
16459       mitchell monte  2026-01-05  134.3       57.113071      -25.9          -0.462500           12.852059                    0.229501                  56.0   0.999696   0.599003         1         1                        0
12091       justice malone  2026-01-19  125.6       39.038154      -29.8          -2.483333            9.743481                    0.811957                  12.0   0.999693   0.539262         1         1                        0
19833     samantha gresham  2026-01-19  106.9       48.254115      -29.0          -2.416667           12.968311                    1.080693                  12.0   0.999569   0.677224         1         1                        0
23059       yuseph mustafa  2025-10-05  185.6       53.148870      -68.2                NaN           22.597592                         NaN                   0.0   0.999558   0.579830         1         1                        0
21138       steve simpkins  2025-11-19  205.1       44.195937      -23.9          -7.966667            5.397235                    1.799078                   3.0   0.999509   0.590733         1         1                        0
22567    vasean washington  2024-05-08  252.4       36.364689      -41.1         -20.550000            7.308624                    3.654312                   2.0   0.999488   0.731861         1         1                        0
20529        sean williams  2025-11-19  164.5       63.094994      -23.4          -7.800000            5.535567                    1.845189                   3.0   0.999479   0.693505         1         1                        0
4190         chase engdahl  2026-01-20  164.5       54.907745      -38.1                NaN           31.153955                         NaN                   0.0   0.999448   0.574345         1         1                        0
3148     cameron davenport  2025-07-15  297.5       35.093877      -68.8          -9.828571            6.425969                    0.917996                   7.0   0.999392   0.687510         1         1                        0
17796        olivia lawlor  2026-01-07   81.9       53.527237      -83.8          -3.643478           30.933156                    1.344920                  23.0   0.999386   0.812133         1         1                        0
11714       joshua johnson  2024-01-25  161.0       62.300169      -86.6          -6.185714           21.075546                    1.505396                  14.0   0.999212   0.827712         1         1                        0
9322        isaiah golonka  2024-05-08  253.7       20.865706      -43.9         -21.950000           -0.099579                   -0.049789                   2.0   0.998574   0.647706         1         1                        0
3121     cameron davenport  2024-05-08  340.6       24.804997      -42.5         -21.250000            1.026121                    0.513060                   2.0   0.998477   0.693957         1         1                        0
12710         katie hansen  2024-01-18  134.2       20.993984      -20.7         -20.700000           -1.601289                   -1.601289                   1.0   0.998409   0.690389         1         1                        0
16931        nick marinaro  2024-05-01  254.2       41.309124      -12.6          -6.300000            5.570678                    2.785339                   2.0   0.998329   0.620317         1         1                        0
4148         chase engdahl  2025-11-05  200.4       14.801872      -42.6          -7.100000            8.472036                    1.412006                   6.0   0.998302   0.703960         1         1                        0
12117          justin ruff  2025-09-19  215.0       26.376114      -45.0         -22.500000           -1.756349                   -0.878175                   2.0   0.998251   0.595977         1         1                        0
3229           cameron lee  2025-09-24  173.9       46.158776      -57.0         -19.000000           -1.594076                   -0.531359                   3.0   0.998086   0.556298         1         1                        0
21732           thai brown  2025-09-24  231.1       46.409850       57.4          19.133333            0.997863                    0.332621                   3.0   0.997806   0.573715         1         1                        0
13643           kyle meier  2025-09-24  247.7       51.453860       12.4           4.133333           11.698469                    3.899490                   3.0   0.997711   0.676187         1         1                        0
2675        bruce williams  2024-04-15   41.3        0.000000     -200.2         -66.733333          -42.475095                  -14.158365                   3.0   0.997502   0.952637         1         1                        0
12920        kellie sutton  2024-08-20   34.4        0.000000     -101.4         -14.485714          -32.883265                   -4.697609                   7.0   0.997502   0.914925         1         1                        0
18049        oskari vuorio  2025-07-01  152.3       39.840559      -35.6         -35.600000            0.784870                    0.784870                   1.0   0.997451   0.586859         1         1                        0
16849       nicholas lemon  2025-09-24  213.9       36.394013       12.3           4.100000          -10.137106                   -3.379035                   3.0   0.997429   0.563272         1         1                        0
9147      immanuel johnson  2025-11-09  172.1       51.854731      -23.4          -3.342857            9.131359                    1.304480                   7.0   0.997257   0.527297         1         1                        0
4184         chase engdahl  2026-01-15  184.3       33.376722      -18.3         -18.300000           11.644309                   11.644309                   1.0   0.996943   0.737892         1         1                        0
18682     quinn stankovits  2026-03-09  188.9       57.961137      -22.1          -3.157143           20.069835                    2.867119                   7.0   0.995768   0.691045         1         1                        0
9393           izzy mundee  2026-02-04  224.0       12.677486       84.8          12.114286          -75.137774                  -10.733968                   7.0   0.995426   0.888066         1         1                        0
4100         chase engdahl  2025-10-09  184.6       36.607038      -16.7         -16.700000            2.346496                    2.346496                   1.0   0.991365   0.547868         1         1                        0
12416           kate riley  2026-02-25  135.9       26.725499      -55.9         -27.950000           -7.592386                   -3.796193                   2.0   0.987710   0.776028         1         1                        0
8331         hailey rorick  2024-10-24  123.5       27.617142      -15.8         -15.800000           -4.734713                   -4.734713                   1.0   0.923525   0.684934         1         1                        0
6982         emma olausson  2025-10-28  110.6       40.274171      -38.9          -4.862500            9.758457                    1.219807                   8.0   0.920026   0.629963         1         1                        0
4155         chase engdahl  2025-11-06  185.2       24.692008      -14.3         -14.300000          -10.729259                  -10.729259                   1.0   0.850677   0.731613         1         1                        0
4252         chase engdahl  2026-02-19  147.6        3.869468      -95.8                NaN           -6.601301                         NaN                   0.0   0.804200   0.528700         1         1                        0
4068         chase engdahl  2025-09-29  187.3       22.636427      -16.6         -16.600000          -11.858568                  -11.858568                   1.0   0.780861   0.773894         1         1                        0
13972          lila browne  2024-04-18  126.1       24.566614      -21.8          -3.114286           -8.351353                   -1.193050                   7.0   0.768761   0.577773         1         1                        0
4248         chase engdahl  2026-02-19  146.4        5.342916      -60.9         -60.900000          -30.904250                  -30.904250                   1.0   0.755736   0.885437         1         1                        0
4204         chase engdahl  2026-02-03  144.2        6.610558      -60.3         -12.060000          -24.611050                   -4.922210                   5.0   0.755478   0.809254         1         1                        0
6264         eli goldstein  2025-05-28  154.6       62.594228      -22.2          -0.600000           15.611345                    0.421928                  37.0   0.752520   0.584632         1         1                        0
12921        kellie sutton  2024-08-27  136.9       32.071945      102.5          14.642857           32.071945                    4.581706                   7.0   0.751130   0.771379         1         1                        0
4262         chase engdahl  2026-02-26  146.5        7.430512      -60.0         -60.000000          -31.286080                  -31.286080                   1.0   0.749929   0.886065         1         1                        0
4224         chase engdahl  2026-02-06  148.2        7.315344      -38.7         -38.700000           -1.510290                   -1.510290                   1.0   0.737414   0.709111         1         1                        0
4212         chase engdahl  2026-02-05  148.7        8.169300      -56.1         -56.100000          -24.614110                  -24.614110                   1.0   0.715080   0.883581         1         1                        0
2676        bruce williams  2024-04-17  242.8       41.558378      201.5         100.750000           41.558378                   20.779189                   2.0   0.647639   0.837035         1         1                        0
4092         chase engdahl  2025-10-03  202.0       17.171478      -40.8         -40.800000           -2.806999                   -2.806999                   1.0   0.503114   0.702137         1         1                        0

In [62]:
final = pd.read_csv("cleaned_data/full_prediction_dataset")
final

,name,date,set,bw_lb,jump_height_cm,force_at_zero_vel,bw_change,bw_change_per_day,jump_height_change,jump_height_change_per_day,days_since_last_test,staff_indicated_anomaly,HGB_score,HGB_pred,ISO_score,ISO_pred,model_indicated_anomaly
0,aaron power,2024-01-23,1,162.1,41.969734,2016.445474,NaN,NaN,NaN,NaN,-1.0,0,0.681138,1,0.037401,0,0
1,abayomi babalola,2024-04-08,1,219.1,40.531239,2665.327931,NaN,NaN,NaN,NaN,-1.0,0,0.000047,0,0.034888,0,0
2,abayomi babalola,2024-04-10,1,219.4,42.815915,2757.147258,0.3,0.150000,2.284676,1.142338,2.0,0,0.000097,0,0.114652,0,0
3,abayomi babalola,2024-04-15,1,219.2,41.563591,2704.433521,-0.2,-0.040000,-1.252324,-0.250465,5.0,0,0.000017,0,0.057327,0,0
4,abayomi babalola,2024-04-17,1,223.5,40.162056,2682.577615,4.3,2.150000,-1.401535,-0.700767,2.0,0,0.000264,0,0.193275,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23400,zyion brown,2025-10-29,1,246.7,42.717731,3349.450791,-5.1,-1.700000,9.385441,3.128480,3.0,0,0.011625,0,0.519243,0,0
23401,zyion brown,2025-11-02,1,251.7,38.390091,3065.137218,5.0,1.250000,-4.327640,-1.081910,4.0,0,0.000109,0,0.256546,0,0
23402,zyion brown,2025-11-05,1,248.2,43.188406,3282.850191,-3.5,-1.166667,4.798315,1.599438,3.0,0,0.001132,0,0.363247,0,0
23403,zyion brown,2025-11-16,1,254.2,38.215138,3148.763451,6.0,0.545455,-4.973268,-0.452115,11.0,0,0.000093,0,0.192156,0,0
23404,zyion brown,2025-11-19,1,250.7,38.052811,3168.681994,-3.5,-1.166667,-0.162327,-0.054109,3.0,0,0.000045,0,0.146863,0,0